### ISSUE TITLE
Twitter is exceding its limits, Is it a problem from my side? 

### ISSUE THREAD

**Issue by Ramachetan** [saurabhnemade/react-twitter-embed#117]
![image](https://user-images.githubusercontent.com/24260211/186071072-116c0a63-3fb5-416b-82d4-bf4d3c0d3897.png)

**Comment by michalpokojski** [comment]
I think something in twitter api changed cause its started to exceeding for me too

**Comment by skhamilton** [comment]
I am also having this same issue. Unsure if there is a work-around to resolve this.
