### ISSUE TITLE
Returning empty div in Next13

### ISSUE THREAD

**Issue by lorenzejay** [saurabhnemade/react-twitter-embed#122]
Migrating to next13, wondering if anyone else is experiencing this once you moved component to app directory.
``` jsx
<>
...
<TwitterTweetEmbed
      tweetId={"xxx"}
      options={{ conversation: "none", cards: "none", link: "none" }}
    />
...
<>
```

**Comment by herlon214** [comment]
@lorenzejay I'm also using NextJS 13 and it's rendering correctly to me.

Did you add `'use client'` to the parent component?

**Comment by lorenzejay** [comment]
Got it working after deleting the node_modules and next folders and retrying next dev. Works now. Actually works as `server component` too.

**Comment by AIEngKenn** [comment]
having the same bug: empty div  :( any help?
