### ISSUE TITLE
react-script and latest storybook dependencies not compatible

### ISSUE THREAD

**Issue by saurabhnemade** [saurabhnemade/react-twitter-embed#15]
Currently react-scripts 2.1.1 requires webpack 4.19.1 however storybook 4.x requires 4.23.1.
Test cases are failing due to this.

**Comment by Philip-Nunoo** [comment]
I think I am having the same error with react-scripts 2.1.1 and storybook 4.x.

**Comment by saurabhnemade** [comment]
@Philip-Nunoo This has been resolved now. You can see the PR #26 .
Somehow my changes are not reflected and build status is still showing wrong. Alternatively you can also take a look at branch https://github.com/saurabhnemade/react-twitter-embed/tree/sn-satyendra-master
