### ISSUE TITLE
border radius on the container

### ISSUE THREAD

**Issue by jtswartz** [saurabhnemade/react-twitter-embed#16]
### Issue:

Cannot override iframe content's `border-radius`. However nice it looks, I need no radius.

<img width="452" alt="screen shot 2018-12-25 at 2 09 33 pm" src="https://user-images.githubusercontent.com/45374663/50426938-716e3f80-084f-11e9-973b-b75507673f18.png">
<img width="962" alt="screen shot 2018-12-25 at 2 10 08 pm" src="https://user-images.githubusercontent.com/45374663/50426939-716e3f80-084f-11e9-9b02-319c07282441.png">
<img width="506" alt="screen shot 2018-12-25 at 2 13 59 pm" src="https://user-images.githubusercontent.com/45374663/50426940-716e3f80-084f-11e9-9ee6-251b3dac56dc.png">

**Comment by filoxo** [comment]
That's because the Twitter API does not allow you to configure this, and you cannot inject any additional styles inside of a shadow DOM. See also the [Twitter Embedded Tweet docs](https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/guides/embedded-tweet-parameter-reference).

**Comment by jtswartz** [comment]
@filoxo I've been looking into this lately still and realize it's pretty much a lost cause to style anything. Appreciate the feedback!

My solution was to roll my own using the API instead.
