### ISSUE TITLE
index.js:2177 Failure to load window.twttr in TwitterTimelineEmbed, aborting load.

### ISSUE THREAD

**Issue by mark-casias** [saurabhnemade/react-twitter-embed#18]
Not able to view the TimelineEmbed in the example site or when I replicate the code locally. Get the above error.

**Comment by mark-casias** [comment]
@saurabhnemade I apologize for this. Turns out it was an adblocker on Chrome.. I had the Disconnect plugin running. I don't think there's anything that needs to / can be done

**Comment by jasonduncan** [comment]
This is still broken
