### ISSUE TITLE
Show Example for hide media on embed

### ISSUE THREAD

**Issue by NickFoden** [saurabhnemade/react-twitter-embed#21]
Took me a minute to figure out how to hide media on embedded tweet. 

Was not clear that you pass:

`options={{ cards: "hidden" }}`

I can submit PR if anyone else agrees. Be good to update storybook and the readme to show this use case as the link to twitter docs is not clear how to achieve hide media of embedded tweets:

[Twitter docs](https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/overview) 
"Set an oEmbed query parameter of hide_media=true or add a data-cards="hidden" attribute to the resulting `<blockquote>` element to prevent expanded content display."

**Comment by saurabhnemade** [comment]
@NickFoden Sure. PR's are welcome. :)
