### ISSUE TITLE
Callback after tweet loading

### ISSUE THREAD

**Issue by DanielBykov** [saurabhnemade/react-twitter-embed#24]
Could you add a callback for TwitterTweetEmbed component firing after a tweet has been loaded? 
I'd like to add a progress spinner to my app, and I need to hide it before a tweet will be shown.
Thanks.

**Comment by carlitosz** [comment]
@DanielBykov Not sure if you're still waiting for this, but according to the docs you can set the callback as such: 

```
<TwitterTweetEmbed tweetId="1083592734038929408" onLoaded={onLoaded} />
```

**Comment by saurabhnemade** [comment]
Api is now unified. `onLoaded` param is now `onLoad`. Please refer to latest docs.
