### ISSUE TITLE
How to center embedded tweet?

### ISSUE THREAD

**Issue by tensor-flower** [saurabhnemade/react-twitter-embed#28]
The embedded tweet sits on the left. I'm trying to center it by justify content, or wrap it inside a `<div>` tag and justify the `<div>` tag, neither works. I also tried display block, margin left auto, margin right auto, also doesn't work. How can I center it though?

**Comment by kepi0809** [comment]
Hi, yeah unfortunately this package make a wrapper div around the iframe which you can't see nor put any options to it… so you have to target it in css. I think the easiest way is to make a wrapper (yeah so 2 wrappers for the same iframe 🙄 ) and add a class to it, then select it in your css (you can use styled component too if you'd like)

then in the css just select the iframe I selected its .twitter-tweet class and it worked for me

here's the code sample: 

    ```
& .twitter-center {
      & > div {
        & > .twitter-tweet{
          margin-left: auto;
          margin-right: auto;
        }
      }
    }
```

hope it helps 👍

**Comment by kepi0809** [comment]
Hi, yeah unfortunately this package make a wrapper div around the iframe which you can't see nor put any options to it… so you have to target it in css. I think the easiest way is to make a wrapper (yeah so 2 wrappers for the same iframe 🙄 ) and add a class to it, then select it in your css (you can use styled component too if you'd like)

then in the css just select the iframe I selected its .twitter-tweet class and it worked for me

here's the code sample: 
```
    & .twitter-center {
      & > div {
        & > .twitter-tweet{
          margin-left: auto;
          margin-right: auto;
        }
      }
    }
```
hope it helps 👍 

PS: it's probably not best practice but at least it works

**Comment by tensor-flower** [comment]
Ok I end up using flex.
```
    <div style={{display:'flex',justifyContent:'center'}}>
      <TwitterTweetEmbed tweetId={'blahblahblah'}/>
    </div>
```

**Comment by ljc-dev** [comment]
> 
> 
> Hi, yeah unfortunately this package make a wrapper div around the iframe which you can't see nor put any options to it… so you have to target it in css. I think the easiest way is to make a wrapper (yeah so 2 wrappers for the same iframe 🙄 ) and add a class to it, then select it in your css (you can use styled component too if you'd like)
> 
> then in the css just select the iframe I selected its .twitter-tweet class and it worked for me
> 
> here's the code sample:
> 
> ```
>     & .twitter-center {
>       & > div {
>         & > .twitter-tweet{
>           margin-left: auto;
>           margin-right: auto;
>         }
>       }
>     }
> ```
> 
> hope it helps 👍
> 
> PS: it's probably not best practice but at least it works

Thanks a lot @kepi0809 😃 ! Just what I needed. Using flex or grid to center would shrink the tweet 😅.
