### ISSUE TITLE
MIME type mismatch for TwitterTweetEmbed

### ISSUE THREAD

**Issue by brentmc79** [saurabhnemade/react-twitter-embed#31]
Getting the following error in the Chrome console when I attempt to render an embedded tweet:

`Refused to execute script from 'https://cdn.syndication.twimg.com/tweets.json?callback=__twttr.callbacks.cb0&ids=zYthtQaw&lang=en&suppress_response_codes=true&theme=light&tz=GMT-0700' because its MIME type ('') is not executable, and strict MIME type checking is enabled.`

Here is the code snippet:

`<TwitterTweetEmbed tweetId="zYthtQaw"/>`

**Comment by KarandikarMihir** [comment]
Can confirm! Any update on this?

**Comment by KarandikarMihir** [comment]
I didn't use this library, but I think the error was because of a leading `/` in tweetId.

**Comment by brentmc79** [comment]
I realized that it was a problem with the string id that I was attempting to use. It was the uid from the shortened tweet url, which isn’t the actual tweet id. As soon as I used a valid id everything worked as expected.
