### ISSUE TITLE
onError or tweet not embedded

### ISSUE THREAD

**Issue by pantchox** [saurabhnemade/react-twitter-embed#37]
Hi,

When loading invalid tweet, for example it was deleted - the component is not showing anything.

is there a way to detect if there was an error loading it and if yes or call a function or set a placeholder component to display instead.

thanks.

**Comment by pantchox** [comment]
found a solution, onLoad funtion utilized it to set wrapped component state to show or hide a loading indicator when finished the returned element if tweet does not exist or error it will be undefined so i display error.

thanks

**Comment by jjg77** [comment]
Thanks for the tip, I did something like this toggling a state variable.

```
<TwitterTweetEmbed 
  tweetId={tweet.chanId} 
  options={{width: Layout.imageWidth}}
  onLoad={event => {
    if(!event){
      setIsMissing(true);
    }
  }}
/>
```
