### ISSUE TITLE
[TwitterTweetEmbed] No target element specified.

### ISSUE THREAD

**Issue by pcorpet** [saurabhnemade/react-twitter-embed#4]
I sometimes have an error `No target element specified. Expected: ƒ(tweetId, target, [options]);` in the console. I think this happens when:
 * I render a ReactTwitterEmbed component as part of my flow
 * The Twitter library gets downloaded/loaded slowly (for instance I'm on a slow network)
 * I remove the ReactTwitterEmbed from my DOM before the Twitter library gets loaded.

I'll send a PR to fix that.

**Comment by saurabhnemade** [comment]
@pcorpet Sure. PRs are welcome. :+1:
