### ISSUE TITLE
Re-rendering component

### ISSUE THREAD

**Issue by anurastogi** [saurabhnemade/react-twitter-embed#44]
I am using the TwitterTweetEmbed component with a variable for the tweetId, in this manner:

`<TwitterTweetEmbed tweetId={item.postID} placeholder="Loading" />`

I have a `<p>{item.postID}</p>` along with this.

On a state change, the item.postID changes, which is reflected in the `<p>` tag, but the `<TwitterTweetEmbed>` still shows the tweet related to the previous postID. 
Anything needed to ensure that the component re-renders?

**Comment by antoinefranz** [comment]
You should add a _key_ to your component:
`<TwitterTweetEmbed key={item.postID} tweetId={item.postID} placeholder="Loading" />`

**Comment by anurastogi** [comment]
Thanks! That helped

**Comment by anurastogi** [comment]
Thanks! That helped.

**Comment by izmarsel** [comment]
Me too. Thanks!!
