### ISSUE TITLE
TwitterTimelineEmbed not rendering updated timeline when changing screenName prop

### ISSUE THREAD

**Issue by pdenya** [saurabhnemade/react-twitter-embed#57]
Changing screenName prop on TwitterTimelineEmbed does not change the displayed timeline. Looks like renderWidget is only called on mount, not on update.

I'm sure there are much cleaner ways to do this so I opted to not submit a pull request but here was my solution. I added the following to TwitterTimelineEmbed.js

```
  componentDidUpdate(prevProps, prevState, snapshot) {
    if (this.props.screenName != prevProps.screenName) {
      /** reset embed Container */
      this.refs.embedContainer.innerHTML = ""

      let options = this.buildOptions()
      /** Append chrome options */
      options = this.buildChromeOptions(options)
      this.renderWidget(options)
    }
  }
```

**Comment by kjain-dev** [comment]
Pass an id attribute as prop to TwitterTimelineEmbed  with unique hash every time.It should wiork
