### ISSUE TITLE
Twitter timeline not work

### ISSUE THREAD

**Issue by thanhvk** [saurabhnemade/react-twitter-embed#87]
Hi, I'm using the twitter-timeline-embed package to display **the timeline of a list** in my project but recently it did not work. And when I use chrome it shows this bug
![Screen Shot 2021-07-30 at 13 42 52](https://user-images.githubusercontent.com/11411161/127611996-1abe8837-b3e9-41e9-8cba-70656545d5cb.png)

The same bug on the demo page
https://saurabhnemade.github.io/react-twitter-embed/?path=/story/twitter-timeline-embed--timeline-profile-with-screen-name

**Comment by vishishttiwari** [comment]
Same here, this has stopped working

**Comment by thanhvk** [comment]
It seems a bug of Twitter because it from https://platform.twitter.com/widgets.js file

**Comment by asnurinsyahirah** [comment]
I fixed the issue by tweaking the solution provided here: https://github.com/andrewsuzuki/react-twitter-widgets/issues/45#issuecomment-889740825

`import { TwitterTimelineEmbed } from 'react-twitter-embed'

export default function App() {
  return (
    <TwitterTimelineEmbed sourceType="profile" screenName="TwitterDev" options={{ id: "profile:TwitterDev" }} />
  );
}
`

Hope this helps!

**Comment by thanhvk** [comment]
@asnurinsyahirah thanks! 
it works for me

```
<TwitterTimelineEmbed
  sourceType="list"
  id="yourlistId"
  options={{height: 500, id:"list:yourlistId"}}
  noScrollbar
  noHeader
/>
```
