### ISSUE TITLE
Can this be done without placing the twitter script in the <head>?

### ISSUE THREAD

**Issue by agonsalves** [saurabhnemade/react-twitter-embed#9]
It feels invasive, unnecessary, and sloppy to add a script to the head that then makes a bunch of calls on page load, even when the Twitter embed is not being displayed. This utility, by simply including it in some conditionally-used component, adds at least 5 additional HTTP requests to the initial load of the page. This places third-party cookies.

Can this not be initialized on the fly, and then removed when unmounted?

**Comment by saurabhnemade** [comment]
@agonsalves Good finding!!  
You got valid point. I am definitely going to look into it sooner. :+1: 

I should make it load on initialisation of any component that mounts first. Removing the script every time on unmount will make a http call to get script on each new instance of widget. So I believe, we can just load it first time & after loading script we can use the same global object to initialise multiple widgets. This way we can save multiple calls, initialise on the fly as well as it will be reused.

**Comment by saurabhnemade** [comment]
#10 fixes this. Closing it.

**Comment by agonsalves** [comment]
@saurabhnemade Thank you for jumping on this so quickly. I did not expect it. This package is back in my project. :)
