### ISSUE TITLE
Option LinkColor

### ISSUE THREAD

**Issue by karlimsc** [saurabhnemade/react-twitter-embed#91]
Hi! The option linkColor is not working even in https://saurabhnemade.github.io/react-twitter-embed/?path=/story/twitter-timeline-embed--timeline-custom-link-color are different colors but the timeline shows the same linkColor.

**Comment by saurabhnemade** [comment]
Unfortunately its removed from official library: https://twittercommunity.com/t/removing-ie11-support-and-custom-link-colors-in-twitter-for-websites/131171

**Comment by karlimsc** [comment]
ok thank u :) 

>
